# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='editable',
            field=models.BooleanField(default=True, editable=False, verbose_name='Editable'),
        ),
    ]
