# Generated by Django 2.2.12 on 2020-06-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_delete_shareduploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLogEntry',
        ),
    ]
