# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-26 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_metadata', '0002_documenttypesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeddriver',
            name='driver_path',
            field=models.CharField(max_length=255, unique=True, verbose_name='Driver path'),
        ),
        migrations.AlterField(
            model_name='storeddriver',
            name='internal_name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Internal name'),
        ),
    ]
