# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0047_auto_20180917_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=96, verbose_name='Label')),
                ('template', models.TextField(verbose_name='Template')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('document_types', models.ManyToManyField(related_name='web_links', to='documents.DocumentType', verbose_name='Document types')),
            ],
            options={
                'ordering': ('label',),
                'verbose_name': 'Web link',
                'verbose_name_plural': 'Web links',
            },
        ),
        migrations.CreateModel(
            name='ResolvedWebLink',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('weblinks.weblink',),
        ),
    ]
