# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20180510_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanescanner',
            name='adf_mode',
            field=models.CharField(blank=True, choices=[('simplex', 'Simplex'), ('duplex', 'Duplex')], help_text='Selects the document feeder mode (simplex/duplex). If this option is not supported by your scanner, leave it blank.', max_length=16, verbose_name='ADF mode'),
        ),
    ]
