# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0018_auto_20180608_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Label'),
        ),
    ]
