# Generated by Django 2.2.12 on 2020-06-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20191219_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceLog',
        ),
    ]
