# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0009_auto_20170807_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowinstancelogentry',
            options={'ordering': ('datetime',), 'verbose_name': 'Workflow instance log entry', 'verbose_name_plural': 'Workflow instance log entries'},
        ),
    ]
