# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0013_auto_20190423_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransitionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Internal name')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('help_text', models.TextField(blank=True, verbose_name='Help text')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='document_states.WorkflowTransition', verbose_name='Transition')),
            ],
            options={
                'verbose_name': 'Workflow transition trigger event',
                'verbose_name_plural': 'Workflow transitions trigger events',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='context',
            field=models.TextField(blank=True, verbose_name='Backend data'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransitionfield',
            unique_together=set([('transition', 'name')]),
        ),
    ]
