from django.utils.translation import ugettext_lazy as _

from icons.literals import *

PATH = 'fat_cow'
ID = 'fat_cow'
LABEL = _(u'Fat cow')

DICTIONARY = {
    APPLICATION_VIEW_ICONS: 'application_view_icons.png',
    BLACKBOARD_SUM: 'blackboard_sum.png',
    BOOK: 'book.png',
    BOOK_GO: 'book_go.png',
    BOOK_OPEN: 'book_open.png',
    CD_BURN: 'cd_burn.png',
    COG: 'cog.png',
    COMPUTER_KEY: 'computer_key.png',
    CROSS: 'cross.png',
    DRAW_AIRBRUSH: 'draw_airbrush.png',
    DOCUMENT_SIGNATURE: 'document_signature.png',
    ERROR: 'error.png',
    GROUP: 'group.png',
    GROUP_ADD: 'group_add.png',
    GROUP_EDIT: 'group_edit.png',
    GROUP_DELETE: 'group_delete.png',
    GROUP_KEY: 'group_key.png',
    INFORMATION: 'information.png',
    KEY: 'key.png',
    KEY_GO: 'key_go.png',
    KEY_ADD: 'key_add.png',
    KEY_DELETE: 'key_delete.png',
    KEYBOARD: 'keyboard.png',
    LAYOUT: 'layout.png',
    LIGHTNING: 'lightning.png',
    LOCK: 'lock.png',
    MAGNIFIER: 'magnifier.png',
    MEDAL_GOLD: 'medal_gold_1.png',
    MEDAL_GOLD_ADD: 'medal_gold_add.png',
    MEDAL_GOLD_DELETE: 'medal_gold_delete.png',
    PAGE: 'page.png',
    PAGE_COPY: 'page_copy.png',
    PAGE_GEAR:'page_gear.png',
    PAGE_DELETE: 'page_delete.png',
    PAGE_EDIT: 'page_edit.png',
    PAGE_REFRESH: 'page_refresh.png',
    PAGE_SAVE: 'page_save.png',
    PAGE_WHITE_COPY: 'page_white_copy.png',
    PAGE_WORLD: 'page_world.png',
    PICTURES: 'pictures.png',
    PILL: 'pill.png',
    PLUGIN: 'plugin.png',
    PRINTER: 'printer.png',
    RAINBOW: 'rainbow.png',
    ROUTING_TURNAROUND_RIGHT: 'routing_turnaround_right.png',
    SCRIPT: 'script.png',
    STORAGE: 'storage.png',
    TABLE: 'table.png',
    TABLE_RELATIONSHIP: 'table_relationship.png',
    TICK: 'tick.png',
    USER: 'user.png',
    USER_ADD:'user_add.png',
    USER_EDIT: 'user_edit.png',
    USER_DELETE: 'user_delete.png',  
    VCARD: 'vcard.png',
    VCARD_EDIT: 'vcard_edit.png',  
    WRENCH: 'wrench.png',
    ZOOM: 'zoom.png',
}
