from django.utils.translation import ugettext_lazy as _

from icons.literals import *

PATH = 'fat_cow'
ID = 'fat_cow'
LABEL = _(u'Fat cow')

DICTIONARY = {
    ADD: 'add.png',
    APPLICATION_VIEW_ICONS: 'application_view_icons.png',
    BLACKBOARD_SUM: 'blackboard_sum.png',
    BOOK: 'book.png',
    BOOK_GO: 'book_go.png',
    BOOK_OPEN: 'book_open.png',
    CAMERA_DELETE: 'camera_delete.png',
    CD_BURN: 'cd_burn.png',
    COG: 'cog.png',
    COG_ADD: 'cog_add.png',
    COG_EDIT: 'cog_edit.png',
    COG_DELETE: 'cog_delete.png',
    COMPUTER_KEY: 'computer_key.png',
    CROSS: 'cross.png',
    DELETE: 'delete.png',
    DRAW_AIRBRUSH: 'draw_airbrush.png',
    DOCUMENT_SIGNATURE: 'document_signature.png',
    ERROR: 'error.png',
    GROUP: 'group.png',
    GROUP_ADD: 'group_add.png',
    GROUP_EDIT: 'group_edit.png',
    GROUP_DELETE: 'group_delete.png',
    GROUP_KEY: 'group_key.png',
    GROUP_LINK: 'group_link.png',
    INFORMATION: 'information.png',
    KEY: 'key.png',
    KEY_GO: 'key_go.png',
    KEY_ADD: 'key_add.png',
    KEY_DELETE: 'key_delete.png',
    KEYBOARD: 'keyboard.png',
    LAYOUT: 'layout.png',
    LIGHTNING: 'lightning.png',
    LINK: 'link.png',
    LINK_ADD: 'link_add.png',
    LINK_EDIT: 'link_edit.png',
    LINK_DELETE: 'link_delete.png',
    LOCK: 'lock.png',
    LOCK_EDIT: 'lock_edit.png',
    MAGNIFIER: 'magnifier.png',
    MEDAL_GOLD: 'medal_gold_1.png',
    MEDAL_GOLD_ADD: 'medal_gold_add.png',
    MEDAL_GOLD_DELETE: 'medal_gold_delete.png',
    PAGE: 'page.png',
    PAGE_COPY: 'page_copy.png',
    PAGE_GEAR:'page_gear.png',
    PAGE_GO: 'page_go.png',
    PAGE_DELETE: 'page_delete.png',
    PAGE_EDIT: 'page_edit.png',
    PAGE_LINK: 'page_link.png',
    PAGE_REFRESH: 'page_refresh.png',
    PAGE_SAVE: 'page_save.png',
    PAGE_WHITE_COPY: 'page_white_copy.png',
    PAGE_WHITE_CSHARP: 'page_white_csharp.png',
    PAGE_WORLD: 'page_world.png',
    PICTURES: 'pictures.png',
    PILL: 'pill.png',
    PLUGIN: 'plugin.png',
    PRINTER: 'printer.png',
    RAINBOW: 'rainbow.png',
    ROUTING_TURNAROUND_RIGHT: 'routing_turnaround_right.png',
    SCRIPT: 'script.png',
    STORAGE: 'storage.png',
    TABLE: 'table.png',
    TABLE_ADD: 'table_add.png',
    TABLE_EDIT: 'table_edit.png',
    TABLE_DELETE: 'table_delete.png',
    TABLE_REFRESH: 'table_refresh.png',
    TABLE_RELATIONSHIP: 'table_relationship.png',
    TAG_BLUE: 'tag_blue.png',
    TAG_BLUE_ADD: 'tag_blue_add.png',
    TAG_BLUE_DELETE: 'tag_blue_delete.png',
    TAG_BLUE_EDIT: 'tag_blue_edit.png',
    TEXT_DROPCAPS: 'text_dropcaps.png',
    TEXT_STRIKETHROUGH: 'text_strikethrough.png',
    TICK: 'tick.png',
    USER: 'user.png',
    USER_ADD:'user_add.png',
    USER_EDIT: 'user_edit.png',
    USER_DELETE: 'user_delete.png',  
    VCARD: 'vcard.png',
    VCARD_EDIT: 'vcard_edit.png',  
    WRENCH: 'wrench.png',
    XHTML: 'xhtml.png',
    XHTML_GO: 'xhtml_go.png',
    XHTML_ADD: 'xhtml_add.png',
    XHTML_DELETE: 'xhtml_delete.png',
    ZOOM: 'zoom.png',
}
