from django.conf import settings

CONFIGURATION_FILENAME = 'config.yml'
CONFIGURATION_LAST_GOOD_FILENAME = 'config_backup.yml'

DEFAULT_ALLOWED_HOSTS = settings.ALLOWED_HOSTS
DEFAULT_APPEND_SLASH = settings.APPEND_SLASH
DEFAULT_AUTH_PASSWORD_VALIDATORS = settings.AUTH_PASSWORD_VALIDATORS
DEFAULT_AUTHENTICATION_BACKENDS = settings.AUTHENTICATION_BACKENDS
DEFAULT_DATABASES = settings.DATABASES
DEFAULT_DATA_UPLOAD_MAX_MEMORY_SIZE = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
DEFAULT_DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL
DEFAULT_DISALLOWED_USER_AGENTS = settings.DISALLOWED_USER_AGENTS
DEFAULT_EMAIL_BACKEND = settings.EMAIL_BACKEND
DEFAULT_EMAIL_HOST = settings.EMAIL_HOST
DEFAULT_EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
DEFAULT_EMAIL_HOST_USER = settings.EMAIL_HOST_USER
DEFAULT_EMAIL_PORT = settings.EMAIL_PORT
DEFAULT_EMAIL_TIMEOUT = settings.EMAIL_TIMEOUT
DEFAULT_EMAIL_USE_TLS = settings.EMAIL_USE_TLS
DEFAULT_EMAIL_USE_SSL = settings.EMAIL_USE_SSL
DEFAULT_FILE_UPLOAD_MAX_MEMORY_SIZE = settings.FILE_UPLOAD_MAX_MEMORY_SIZE
DEFAULT_LOGIN_URL = settings.LOGIN_URL
DEFAULT_LOGIN_REDIRECT_URL = settings.LOGIN_REDIRECT_URL
DEFAUTL_LOGOUT_REDIRECT_URL = settings.LOGOUT_REDIRECT_URL
DEFAULT_INTERNAL_IPS = settings.INTERNAL_IPS
DEFAULT_LANGUAGES = settings.LANGUAGES
DEFAULT_LANGUAGE_CODE = settings.LANGUAGE_CODE
DEFAULT_SESSION_COOKIE_NAME = settings.SESSION_COOKIE_NAME
DEFAULT_SESSION_ENGINE = settings.SESSION_ENGINE
DEFAULT_SECURE_PROXY_SSL_HEADER = settings.SECURE_PROXY_SSL_HEADER
DEFAULT_STATIC_URL = settings.STATIC_URL
DEFAULT_STATICFILES_STORAGE = settings.STATICFILES_STORAGE
DEFAULT_TIME_ZONE = settings.TIME_ZONE
DEFAULT_USE_X_FORWARDED_HOST = settings.USE_X_FORWARDED_HOST
DEFAULT_USE_X_FORWARDED_PORT = settings.USE_X_FORWARDED_PORT,
DEFAULT_WSGI_APPLICATION = settings.WSGI_APPLICATION

NAMESPACE_VERSION_INITIAL = '0001'
SMART_SETTINGS_NAMESPACES_NAME = 'SMART_SETTINGS_NAMESPACES'
