# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 07:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import document_signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_signatures', '0007_auto_20180403_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachedsignature',
            name='signature_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/rosarior/development/mayan-edms/mayan/media/document_signatures'), upload_to=document_signatures.models.upload_to, verbose_name='Signature file'),
        ),
    ]
