from __future__ import unicode_literals

TEST_CORRECT_LOOKUP_VALUE = '1'
TEST_DATE_PARSER = 'metadata.parsers.DateParser'
TEST_DATE_VALIDATOR = 'metadata.validators.DateValidator'
TEST_DEFAULT_VALUE = 'test'
TEST_INCORRECT_LOOKUP_VALUE = '0'
TEST_INVALID_DATE = '___________'
TEST_LOOKUP_TEMPLATE = '1,2,3'
TEST_METADATA_TYPE_NAME = 'test'
TEST_METADATA_TYPE_LABEL = 'test'
TEST_PARSED_VALID_DATE = '2001-01-01'
TEST_VALID_DATE = '2001-1-1'
