__title__ = 'Mayan EDMS'
__version__ = '4.0.5'
__build__ = 0x040005
__build_string__ = 'v4.0.5-4-geb76f4dc25_Tue Jun 8 23:48:33 2021 -0400'
__django_version__ = '2.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'Apache 2.0'
__copyright_short__ = '2011 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
