# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mayan.apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=196, unique=True, verbose_name='Label')),
            ],
            options={
                'ordering': ('label',),
                'verbose_name': 'Control sheet',
                'verbose_name_plural': 'Control sheets',
            },
        ),
        migrations.CreateModel(
            name='ControlSheetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, db_index=True, default=0, help_text='Order in which the transformations will be executed. If left unchanged, an automatic order value will be assigned.', verbose_name='Order')),
                ('name', models.CharField(choices=[('test', 'Test: argument_1')], max_length=128, verbose_name='Name')),
                ('arguments', models.TextField(blank=True, help_text='Enter the arguments for the control code as a YAML dictionary.', validators=[mayan.apps.common.validators.YAMLValidator()], verbose_name='Arguments')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('control_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='control_codes.ControlSheet', verbose_name='Control sheet')),
            ],
            options={
                'verbose_name': 'Control sheet code',
                'verbose_name_plural': 'Control sheet codes',
            },
        ),
    ]
