# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial_squashed_0008_auto_20180310_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttypemetadatatype',
            options={'ordering': ('metadata_type',), 'verbose_name': 'Document type metadata type options', 'verbose_name_plural': 'Document type metadata types options'},
        ),
    ]
