#from icons.sets import fat_cow, famfamfam

#DEFAULT_ICON_SET = fat_cow.ID
DEFAULT_ICON_SET = 'fat_cow'

   
APPLICATION_VIEW_ICONS = 'application_view_icons'
BLACKBOARD_SUM = 'blackboard_sum'
BOOK = 'book'
BOOK_OPEN = 'book_open'
CD_BURN = 'cd_burn'
COG = 'cog'
COMPUTER_KEY = 'computer_key'
CROSS = 'cross'
DRAW_AIRBRUSH = 'draw_airbrush'
ERROR = 'error'
GROUP = 'user',
GROUP_ADD = 'group_add'
GROUP_EDIT = 'group_edit'
GROUP_DELETE = 'group_delete'
GROUP_KEY = 'group_key'
INFORMATION = 'information'
KEY = 'key'
KEY_GO = 'key_go'
KEY_ADD = 'key_add'
KEY_DELETE = 'key_delete'
KEYBOARD = 'keyboard'
LIGHTNING = 'lightning'
LOCK = 'lock'
MEDAL_GOLD = 'medal_gold'
MEDAL_GOLD_ADD = 'medal_gold_add'
MEDAL_GOLD_DELETE = 'medal_gold_delete'
PICTURES = 'pictures'
PILL = 'pill'
PLUGIN = 'plugin'
RAINBOW = 'rainbow'
SCRIPT = 'script'
STORAGE = 'storage'
TABLE = 'table'
TICK = 'tick'
USER = 'user'
USER_ADD = 'user_add'
USER_EDIT = 'user_edit'
USER_DELETE = 'user_delete'
VCARD = 'vcard'
VCARD_EDIT = 'vcard_edit'
WRENCH = 'wrench'
