# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-16 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayan_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticresult',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
