from django.utils.translation import ugettext_lazy as _

DEFAULT_NODE_HEARTBEAT_INTERVAL = 10
DEFAULT_NODE_HEARTBEAT_TIMEOUT = 60
DEFAULT_DEAD_NODE_REMOVAL_INTERVAL = 10

NODE_STATE_HEALTHY = 'h'
NODE_STATE_DEAD = 'd'

NODE_STATE_CHOICES = (
    (NODE_STATE_HEALTHY, _(u'healthy')),
    (NODE_STATE_DEAD, _(u'dead')),
)

DEFAULT_JOB_QUEUE_POLL_INTERVAL = 2
DEFAULT_NODE_CPU_LOAD = 0
DEFAULT_NODE_MEMORY_USAGE = 0
