# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0015_auto_20190814_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transformation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Transformation',
        ),
    ]
