# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 07:02
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_auto_20170823_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'mayan/media/document_storage'), upload_to=documents.models.UUID_FUNCTION, verbose_name='File'),
        ),
    ]
