# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-08 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0053_auto_20191007_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentPageResult',
        ),
        migrations.CreateModel(
            name='DocumentVersionPageResult',
            fields=[
            ],
            options={
                'verbose_name': 'Document version page',
                'verbose_name_plural': 'Document version pages',
                'ordering': ('document_version__document', 'page_number'),
                'proxy': True,
                'indexes': [],
            },
            bases=('documents.documentversionpage',),
        ),
    ]
