# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0054_auto_20191008_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('page_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Page number')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.Document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document page',
                'verbose_name_plural': 'Document pages',
                'ordering': ('page_number',),
            },
        ),
        migrations.AlterModelOptions(
            name='documentversionpage',
            options={'ordering': ('page_number',), 'verbose_name': 'Document version page', 'verbose_name_plural': 'Document version pages'},
        ),
        migrations.AlterField(
            model_name='documentversionpage',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.DocumentVersion', verbose_name='Document version'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together=set([('document', 'page_number')]),
        ),
    ]
