# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('dotted_path', models.CharField(max_length=128, verbose_name='Dotted path')),
            ],
            options={
                'verbose_name': 'Field choice',
                'verbose_name_plural': 'Field choices',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Form template',
                'verbose_name_plural': 'Form templates',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FormTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('arguments', models.TextField(blank=True, verbose_name='Arguments')),
                ('widget', models.CharField(blank=True, max_length=128, verbose_name='Widget')),
                ('widget_arguments', models.CharField(blank=True, max_length=128, verbose_name='Widget arguments')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='forms.FieldChoice', verbose_name='Choice')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.FormTemplate', verbose_name='Form template field')),
            ],
            options={
                'verbose_name': 'Form template field',
                'verbose_name_plural': 'Form template fields',
            },
        ),
    ]
